name: firebase_auth_verify_email
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  #">=2.12.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter


  cupertino_icons: ^1.0.4

  # Firebase
  firebase_auth: ^4.14.1

  # Validate Email
  email_validator: ^2.1.17
  cloud_firestore: ^4.13.2
  firebase_core: ^2.23.0
  google_sign_in: ^6.1.6
  firebase_storage: ^11.5.2
  provider: ^6.1.1
  flex_color_scheme: ^7.3.1
  firebase_database: ^10.3.5
  easy_sidemenu: ^0.5.0
  sidebarx: ^0.16.3
  intl: ^0.19.0
  sign_in_button: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/insignia.png
  
  fonts:
    - family: ArmyAircraft
      fonts:
        - asset: assets/ArmyAircraft.ttf
