// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzdCJeTJFvSeGQXW_i8XmvYz-ZQ0anNY',
    appId: '1:783611860349:web:62975f88ab0c64bb8e2814',
    messagingSenderId: '783611860349',
    projectId: 'fir-auth-verify-email',
    authDomain: 'fir-auth-verify-email.firebaseapp.com',
    storageBucket: 'fir-auth-verify-email.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf1QCjaspJ74G-QrNsW73IJhOUKzJn2tg',
    appId: '1:783611860349:android:db44c5ed51ac75b58e2814',
    messagingSenderId: '783611860349',
    projectId: 'fir-auth-verify-email',
    storageBucket: 'fir-auth-verify-email.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIcSy-bvdnSEwxL7xXKQ1AhsHgwVWzaY',
    appId: '1:783611860349:ios:4b2cd6877c6a0e2d8e2814',
    messagingSenderId: '783611860349',
    projectId: 'fir-auth-verify-email',
    storageBucket: 'fir-auth-verify-email.appspot.com',
    iosClientId: '783611860349-e6bo9nolt96qtuqpm5en2v6ebm565g0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthVerifyEmail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxIcSy-bvdnSEwxL7xXKQ1AhsHgwVWzaY',
    appId: '1:783611860349:ios:4b2cd6877c6a0e2d8e2814',
    messagingSenderId: '783611860349',
    projectId: 'fir-auth-verify-email',
    storageBucket: 'fir-auth-verify-email.appspot.com',
    iosClientId: '783611860349-e6bo9nolt96qtuqpm5en2v6ebm565g0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthVerifyEmail',
  );
}
